### PR TITLE
Upstream v3.ocaml.org fork

### PR DESCRIPTION
**Pull request by tmattio**
Hi!

We're using a fork of river to fetch the RSS feeds in https://v3.ocaml.org/blog.

The fork consists essentially of:

- Porting the build system to Dune
- Changing the API to make the types abstract and add functions for the different fields
- Add some information that can be gathered by fetching the link provided in the post (e.g. the meta description, and the SEO image)

The diff is quite large, so understandably you might not want to merge as-is, but let me know if you're interested in merging some parts of the changes above, or if you would like me to split the PR.

### CODE REVIEW

**Comment by kayceesrk** [comment]
Hi @tmattio, the project hasn’t been maintained for many years. I was surprised that you are using it. :-) If you are interested, I’m happy to transfer this repo to the right org, and you can manage it however you want. 

In the meantime, I’ll merge the PR as is.

**Comment by tmattio** [comment]
Thanks @kayceesrk!

It would be useful to cut a release on opam so we can use a released version for v3.ocaml.org. If you want, I can do this and continue to maintain the project as we're actively using it 🙂 

I'm not sure what the best home for the project is, but I'd be happy to transfer it to tmattio/river or manage it on kayceesrk/river if you want to give me permission. As you prefer!

**Comment by kayceesrk** [comment]
I've added you as a collaborator. I assume this means you have write access to the repo. I tried transferring the repo to your Github account, but was unable to do since `tmattio/river` already exists. If you can do something about the existing `tmattio/river` (rename or delete), I can try transferring again.

**Comment by tmattio** [comment]
Thanks a lot @kayceesrk! I've deleted my fork so it should work now, but I also really don't mind maintaining the project on your account 🙂

**Comment by kayceesrk** [comment]
Ok. I've kicked off the transfer. :-)

**Pull request merged**
